### ISSUE TITLE
prepay_id 怎么获取啊，你这里找不到怎么用

### ISSUE THREAD

**Issue by sunhacker** [binarywang/weixin-java-pay-demo#10]
prepay_id 怎么获取啊，你这里找不到怎么用，谢谢

**Comment by binarywang** [comment]
看统一下单接口的返回值

**Comment by sunhacker** [comment]
大神可否帮我看一下，用了你的支付模块，怎么调试都不行啊！

**Comment by binarywang** [comment]
注意阅读官方文档，同时可以参考https://github.com/wechat-group/weixin-java-tools/wiki/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98

**Comment by guotie** [comment]
同问

**Comment by guotie** [comment]
小程序支付用哪个返回值？

**Comment by binarywang** [comment]
请不要在已关闭issue下提问，请新建issue并清晰准确描述你的问题，谢谢合作
