### ISSUE TITLE
v3支付回调，提示非法请求，头部信息验证失败

### ISSUE THREAD

**Issue by pigping88** [binarywang/weixin-java-pay-demo#109]
@PostMapping("/notify-order-v3")
    public WxPayResponseVO wxPayOrderNotify(@RequestBody OriginNotifyForm notifyResponse,
                                            @RequestHeader HttpHeaders headers) throws WxPayException {
        try {
            String jsonStr = JSONUtil.toJsonStr(notifyResponse);
            SignatureHeader signatureHeader = getSignatureHeaderByHttpHeaders(headers);

            log.info(JSONUtil.toJsonStr(signatureHeader));
            if (notifyResponse.getSummary().equals("支付成功")) {
                orderService.handleWxPayOrderNotify(signatureHeader, jsonStr);
            }
        }catch (Exception e) {
            log.error(e.getMessage(), e);
        }

        return new WxPayResponseVO()
                .setCode(WxPayConstants.ResultCode.SUCCESS)
                .setMessage("成功");
    }

private SignatureHeader getSignatureHeaderByHttpHeaders(HttpHeaders headers) {
        SignatureHeader signatureHeader = new SignatureHeader();
        signatureHeader.setSignature(headers.getFirst("Wechatpay-Signature"));
        signatureHeader.setSerial(headers.getFirst("Wechatpay-Serial"));
        signatureHeader.setTimeStamp(headers.getFirst("Wechatpay-Timestamp"));
        signatureHeader.setNonce(headers.getFirst("Wechatpay-Nonce"));
        return signatureHeader;
    }

源码：
@Override
  public WxPayOrderNotifyV3Result parseOrderNotifyV3Result(String notifyData, SignatureHeader header) throws WxPayException {
    if (Objects.nonNull(header) && !this.verifyNotifySign(header, notifyData)) {
      throw new WxPayException("非法请求，头部信息验证失败");
    }
    OriginNotifyResponse response = GSON.fromJson(notifyData, OriginNotifyResponse.class);
    OriginNotifyResponse.Resource resource = response.getResource();
    String cipherText = resource.getCiphertext();
    String associatedData = resource.getAssociatedData();
    String nonce = resource.getNonce();
    String apiV3Key = this.getConfig().getApiV3Key();
    try {
      String result = AesUtils.decryptToString(associatedData, nonce, cipherText, apiV3Key);
      WxPayOrderNotifyV3Result.DecryptNotifyResult decryptNotifyResult = GSON.fromJson(result, WxPayOrderNotifyV3Result.DecryptNotifyResult.class);
      WxPayOrderNotifyV3Result notifyResult = new WxPayOrderNotifyV3Result();
      notifyResult.setRawData(response);
      notifyResult.setResult(decryptNotifyResult);
      return notifyResult;
    } catch (GeneralSecurityException | IOException e) {
      throw new WxPayException("解析报文异常！", e);
    }
  }

提示失败，查看了下Wechatpay-Serial序列号和 WxPayConfig下面的序列号不一致
 /**
   * apiV3 证书序列号值
   */
  private String certSerialNo;

**Comment by pigping88** [comment]
回调可以解密，但是无法验证头部信息

**Comment by pigping88** [comment]
查看文档说是用平台证书验证，找了一圈，没发现相关方法，配置啥的

**Comment by ivendear** [comment]
大哥你问题解决了吗，我也遇到了

**Comment by ivendear** [comment]
我解决了，不能用`OriginNotifyForm notifyResponse`来接收，换成`Map<String, Object> map`就好了

**Comment by renanmin** [comment]
这是来自QQ邮箱的疫情自动回复邮件。
 
您好，我最近正在疫情中，无法亲自回复您的邮件。我将在疫情结束后，尽快给您回复。
