### ISSUE TITLE
统一下单接口怎么查看返回的错误码和信息

### ISSUE THREAD

**Issue by Roronoa-Zoro** [binarywang/weixin-java-pay-demo#11]
WxPayUnifiedOrderResult unifiedOrder(WxPayUnifiedOrderRequest request) throws WxPayException;
这个接口的返回值，并没有去反序列化那些错误信息，是否可以加上获取有其他途径可以获取？

**Comment by binarywang** [comment]
异常里有详细错误信息

**Comment by Roronoa-Zoro** [comment]
是我没注意看，而且WxPayUnifiedOrderResult这个对象也继承了一个基类，里面包括了其他信息，感谢回复。
