### ISSUE TITLE
有没有：商家转账到零钱API（不是企业转账到零钱）

### ISSUE THREAD

**Issue by willfcareer** [binarywang/weixin-java-pay-demo#110]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
有没有商家转账到零钱API，强调：不是企业转账到零钱

### 版本情况

* WxJava 版本号:4.4.0

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__日志内容如果过多，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
请自行在WxJava里搜索下官方文档对应的接口地址看是否存在，有问题在WxJava SDK里提出，谢谢

**Comment by renanmin** [comment]
这是来自QQ邮箱的疫情自动回复邮件。
 
您好，我最近正在疫情中，无法亲自回复您的邮件。我将在疫情结束后，尽快给您回复。
