### ISSUE TITLE
微信统一下单接口生成签名有问题

### ISSUE THREAD

**Issue by dantefung** [binarywang/weixin-java-pay-demo#12]
“
1、签名算法
（签名校验工具）
签名生成的通用步骤如下：
第一步，设所有发送或者接收到的数据为集合M，将集合M内非空参数值的参数按照参数名ASCII码从小到大排序（字典序），使用URL键值对的格式（即key1=value1&key2=value2…）拼接成字符串stringA。
特别注意以下重要规则：
◆ 参数名ASCII码从小到大排序（字典序）；
◆ 如果参数的值为空不参与签名；
◆ 参数名区分大小写；
◆ 验证调用返回或微信主动通知签名时，传送的sign参数不参与签名，将生成的签名与该sign值作校验。
◆ 微信接口可能增加字段，验证签名时必须支持增加的扩展字段
第二步，在stringA最后拼接上key得到stringSignTemp字符串，并对stringSignTemp进行MD5运算，再将得到的字符串所有字符转换为大写，得到sign值signValue。
◆ key设置路径：微信商户平台(pay.weixin.qq.com)-->账户设置-->API安全-->密钥设置
举例：
”
**重点：◆ 如果参数的值为空不参与签名；**
“  public static String createSign(Map<String, String> params, String signKey, String signType) {
        SortedMap<String, String> sortedMap = new TreeMap(params);
        StringBuilder toSign = new StringBuilder();
        Iterator var5 = sortedMap.keySet().iterator();

        while(var5.hasNext()) {
            String key = (String)var5.next();
            String value = (String)params.get(key);
            if(!Lists.newArrayList(new String[]{"sign", "key", "sign_type"}).contains(key)) {
                toSign.append(key).append("=").append(value).append("&");
            }
        } // 这里没有做排除参数值为空的处理，请及时修正

        toSign.append("key=").append(signKey);
        if("HMAC-SHA256".equals(signType)) {
            return createHMACSha256Sign(toSign.toString(), signKey);
        } else {
            return DigestUtils.md5Hex(toSign.toString()).toUpperCase();
        }
    }”

**Comment by binarywang** [comment]
感谢提出此问题，是2.8.2.BETA这个版本产生的bug，稍后修复下，你可以改成2.8.1.BETA或者2.8.0版本，应该没有问题

**Comment by binarywang** [comment]
或者使用最新测试版本2.8.3.BETA

**Comment by dantefung** [comment]
您好，代码还有一处是有问题的:
WxPayUnifiedOrderRequest类中
   protected void checkConstraints() throws WxPayException {
        if("JSAPI".equals(this.getTradeType()) && this.getOpenid() == null && this.getSubOpenid() == null) {
            throw new WxPayException("当 trade_type是'JSAPI'时未指定openid或sub_openid");
        } else if("NATIVE".equals(this.getTradeType()) && this.getProductId() == null) {
            throw new WxPayException("当 trade_type是'NATIVE'时未指定product_id");
        }
    }
微信内H5支付文档:https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1
微信H5支付文档https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_1
中均没有sub_openid，代码做了强制非null判断。
我因为传“”绕过该判断才发现签名算法的bug。请合理修复下，谢谢~

**Comment by binarywang** [comment]
sub_openid是服务商模式下会出现的，所以你在普通模式的文档里看不到

**Comment by dantefung** [comment]
原来如此，谢谢
