### ISSUE TITLE
服务商模式V3-API

### ISSUE THREAD

**Issue by JunMoXiao777** [binarywang/weixin-java-pay-demo#124]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述

微信支付，服务商模式V3API 不支持。

### 版本情况

* WxJava 版本号: 4.5.0

### 期待结果
希望支持服务商V3API一套

### 实际情况
现在原来下单V3 枚举类的地址全是直连商户的

**Comment by binarywang** [comment]
麻烦提交问题到WxJava里，并准确表达你的问题，谢谢
