### ISSUE TITLE
退款通知回调时，wxService.parseRefundNotifyResult抛出Illegal key size or default parameters异常

### ISSUE THREAD

**Issue by tenonersoft** [binarywang/weixin-java-pay-demo#15]
退款通知回调时，wxService.parseRefundNotifyResult抛出Illegal key size or default parameters异常
具体为 cipher.init(Cipher.DECRYPT_MODE, key);时报错
 /**
   * 从xml字符串创建bean对象
   *
   * @param xmlString xml字符串
   * @param mchKey    商户密钥
   */
  public static WxPayRefundNotifyResult fromXML(String xmlString, String mchKey) throws WxPayException {
    WxPayRefundNotifyResult result = WxPayBaseResult.fromXML(xmlString, WxPayRefundNotifyResult.class);
    String reqInfoString = result.getReqInfoString();
    try {
      Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");

      final MessageDigest md5 = MessageDigest.getInstance("MD5");
      md5.update(mchKey.getBytes());
      final String keyMd5String = new BigInteger(1, md5.digest()).toString(16).toLowerCase();
      SecretKeySpec key = new SecretKeySpec(keyMd5String.getBytes(), "AES");
      cipher.init(Cipher.DECRYPT_MODE, key);
      result.setReqInfo(ReqInfo.fromXML(new String(cipher.doFinal(Base64.decodeBase64(reqInfoString)))));
    } catch (Exception e) {
      throw new WxPayException("解密退款通知加密信息时出错", e);
    }

    return result;
  }

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/issues/357 问题重复，关闭
