### ISSUE TITLE
WxPayService的配置线程安全问题

### ISSUE THREAD

**Issue by zhanghengtodo** [binarywang/weixin-java-pay-demo#16]
有多个不同的商户（mchId、mchKey、appId）在使用WxPayService时，每次调用getPayInfo之前，设置wxPayService.setConfig和unifiedOrderRequset.setAppid，会有线程不安全的问题吗？
或者说每次设置配置后，假如某次支付时不设置配置，取的配置上一次设置的配置还是配置文件里wechat.pay.*的配置？

**Comment by binarywang** [comment]
1. 如果wxPayService是单例的，那肯定有问题了。
2. 当然是读取你上一次设置的配置了。

建议你将各个商户的配置放在map或缓存中，自己实现config，每次支付前，使用threadlocal设置对应的商户配置（或者map的key什么的），在支付时读取配置也从threadlocal里读取，这样可以相当于传递了参数，又保证了线程安全。

**Comment by zhanghengtodo** [comment]
非常感谢，自己试了下的确会有问题。已经按照你给的思路重新实现了相关的方法，测试了没有问题。
