### ISSUE TITLE
能否提供支付宝支付功能呢？

### ISSUE THREAD

**Issue by jiangzhixiao** [binarywang/weixin-java-pay-demo#17]
代码写的非常好，代码很简介，逻辑划分非常清晰。支付这一块能否集成支付宝？

**Comment by binarywang** [comment]
不是同一架构，没必要揉在同一个项目里，而且网上支付宝的支持也已经有很多了吧

**Comment by jiangzhixiao** [comment]
@binarywang 这倒也是，主要考虑支付不想分多个项目部署，支付宝这块能不能推荐一下？谢谢老兄！

**Comment by binarywang** [comment]
不清楚了，没做过相关开发
