### ISSUE TITLE
H5支付

### ISSUE THREAD

**Issue by CentMeng** [binarywang/weixin-java-pay-demo#18]
希望新的版本增加H5支付

**Comment by binarywang** [comment]
所有接口都已实现，不知道你所谓的支持是什么意思？

**Comment by CentMeng** [comment]
tradetype为MWEB类型的，有实现吗？

**Comment by CentMeng** [comment]
自己重新写了个类已解决，如有更好的方式解决，麻烦告诉一下

**Comment by binarywang** [comment]
如果你说的是createOrder方法的支持，其实也很简单，增加一个实现类即可，里面只有一个属性mwebUrl

**Comment by CentMeng** [comment]
嗯，我就是这样实现的

**Comment by binarywang** [comment]
最新版本已支持，你可以查看下
