### ISSUE TITLE
http://localhost:8080/pay/unifiedOrder用post请求,现在报错了,咋整,是不是缺参数

### ISSUE THREAD

**Issue by ithjz** [binarywang/weixin-java-pay-demo#19]
{"timestamp":1526355191681,"status":415,"error":"Unsupported Media Type","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported","path":"/pay/unifiedOrder","URL":"http://localhost:8080/error"}

**Comment by ithjz** [comment]
http://localhost:8080/pay/unifiedOrder怎么测试这个接口呀?大神

**Comment by binarywang** [comment]
需要传参数到body中，而且content_type要正确。如果你不习惯这种方式，可以自己改造相应接口
