### ISSUE TITLE
微信退款，如果result_code为FAIL是会出现空指针异常

### ISSUE THREAD

**Issue by lijianfx** [binarywang/weixin-java-pay-demo#22]
微信退款，如果result_code为FAIL是会出现空指针异常，并且BaseWxPayServiceImpl类refund方法无法捕获该异常， throws WxPayException无效。
![image](https://user-images.githubusercontent.com/29617189/43513157-9ea0aef6-95af-11e8-8301-ed77dcb51254.png)

![image](https://user-images.githubusercontent.com/29617189/43513134-8d2fb284-95af-11e8-9dd6-207b04f700ae.png)

**Comment by binarywang** [comment]
这个问题已经修复了，看develop分支代码，或者使用最新测试版本，下次问问题前可以看下之前他人的提问题记录，省的都已经解决了，你还费劲贴这么多图，何苦呢？

**Comment by lijianfx** [comment]
谢了！
