### ISSUE TITLE
在WxPayService，如果是多个公众号时，要如何注入呢？

### ISSUE THREAD

**Issue by zeopean** [binarywang/weixin-java-pay-demo#23]
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-08-15 15:44:01.922 ERROR 70280 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.stylefeng.guns.rest.domain.service.trade.impl.WechatPayServiceImpl required a bean of type 'com.github.binarywang.wxpay.service.WxPayService' that could not be found.

**Comment by binarywang** [comment]
你这个错误信息跟标题所说是两个问题吧？
