### ISSUE TITLE
支付建议

### ISSUE THREAD

**Issue by cjcj125125** [binarywang/weixin-java-pay-demo#24]
看了一下代码，感觉挺可以的，希望可以把微信app支付结合进来

**Comment by asd8517795** [comment]
#1.对参数按照key=value的格式，并按照参数名ASCII字典序排序生成字符串：
appid=wxab503a5b4a8f7af2&body=asd&mch_id=1520905631&nonce_str=1545708407904&notify_url=http://www.weixin.qq.com/wxpay/pay.php&out_trade_no=20181222154825451&spbill_create_ip=113.87.182.6&total_fee=30000&trade_type=APP

**Comment by asd8517795** [comment]
使用该sdk,接入微信支付时,总是报签名错误,打印请求参数,不是这个顺序,有相关关系嘛?

**Comment by binarywang** [comment]
签名参数没问题，你仔细调试下就知道了

**Comment by asd8517795** [comment]
嗯,签名工具验证了,签名通过,顺序没有问题. 关于签名错误的问题,已经仔细检查传参无误,并且重置了两次AppSecret. 还是签名错误,大神有啥建议吗?

**Comment by binarywang** [comment]
仔细检查下各个参数，看是否有漏的和值不合要求的

**Comment by asd8517795** [comment]
非常感谢您的耐心回答, 此问题已解决, 签名加密算法通过验证工具的话,参数数量与参数名也确认无误,请检查自己的密匙 (mchKey),是否在商户中心->api安全中设置您的密匙,再添加到url尾部参与签名.mchKey 不是应用下的AppSecret
