### ISSUE TITLE
notify_url 是不是不支持 后台 配置自动填充啊？

### ISSUE THREAD

**Issue by itsguo** [binarywang/weixin-java-pay-demo#27]
看了下源码：
![image](https://user-images.githubusercontent.com/24457961/56859463-ebf5ca00-69bd-11e9-8094-4b2eeb87b5fb.png)
这边有@Required 这个注解。
这样 notify_url 只能靠前台 代码传了啊？我是希望这个 notify_url  也是根据我后台配置来决定.

**Comment by binarywang** [comment]
这个@Required注解的意思是接口请求到微信时必须有值，跟你的实现无关。
