### ISSUE TITLE
支付回调通知处理可以返回ok吗？

### ISSUE THREAD

**Issue by sxz1314** [binarywang/weixin-java-pay-demo#28]
return WxPayNotifyResponse.success("OK");

**Comment by WenBinJiang** [comment]
> return WxPayNotifyResponse.success("OK");

这个好用吗，老哥

**Comment by sxz1314** [comment]
> > 返回WxPayNotifyResponse.success（“OK”）;
> 
> 这个好用吗，老哥

我后来自己写了回复
