### ISSUE TITLE
微信支付多门店支付，接入比较麻烦

### ISSUE THREAD

**Issue by rottenmu** [binarywang/weixin-java-pay-demo#29]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:wxjava-3.3.0

### 期待结果
微信支付多门店支付接入比较麻烦，
希望，wxjava提供一个handler接口或者内部实现多个wxpayService的封装，最好
app_id作为key
### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
请确认下你所发的内容，移除无用部分，太多干扰
