### ISSUE TITLE
微信支付能否支持多个appid

### ISSUE THREAD

**Issue by JoneYing** [binarywang/weixin-java-pay-demo#30]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）
微信支付能否支持多个appid?
### 简要描述

多个小程序共用一个服务端时,如何配置多个appid

### 版本情况

* WxJava 版本号:
3.3.0

### 期待结果
__尽量详细描述__

### 实际情况
在配置微信支付参数时,目前只看到配置单个demo,如何配置多个? 如下图
![image](https://user-images.githubusercontent.com/45870562/59197731-93bd0500-8bc4-11e9-8c07-f8f55a93461e.png)

**Comment by binarywang** [comment]
可以参考公众号demo进行改造
