### ISSUE TITLE
企业付款到零钱

### ISSUE THREAD

**Issue by 776727328** [binarywang/weixin-java-pay-demo#33]
# 问题 
   企业微信付款到零钱提示“【异常信息】：请确保商户号mchId已设置”

### 简要描述
   商户类型是“普通商户”，商户号直接复制粘贴过来的，请问还需要去哪里设置商户号？
<xml>
  <nonce_str>5468abf4-4eb7-4ae5-8f93-754fb5ec</nonce_str>
  <sign>FA9A20528CE83A6403E7C7FE95859267</sign>
  <mch_appid>************</mch_appid>
  <mchid>********</mchid>
  <partner_trade_no>10000098201411111234567890</partner_trade_no>
  <openid>********</openid>
  <check_name>FORCE_CHECK</check_name>
  <re_user_name>********</re_user_name>
  <amount>1</amount>
  <desc>提现</desc>
  <spbill_create_ip>192.168.10.164</spbill_create_ip>
</xml>
【异常信息】：请确保商户号mchId已设置

### 版本情况

* WxJava 版本号:

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
配置文件，自己阅读下源码就一切很清楚了
