### ISSUE TITLE
证书怎么配置？

### ISSUE THREAD

**Issue by 776727328** [binarywang/weixin-java-pay-demo#34]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）
请问下我证书下载下来之后，怎么配置？
你配置文件中注释写着：p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
绝对路劲我试过是可以的，请问怎么用指定类路劲呢？
我把证书文件放到resources目录下， 然后 keyPath: classes:apiclient_cert.p12    提示说：证书不存在。请指教下 。谢谢

### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by niuwang** [comment]
classpath:提示证书不对，只有绝对路径可以

**Comment by binarywang** [comment]
`classes:` 楼主为什么要加这个？
