### ISSUE TITLE
统一下单返回正确但内存溢出

### ISSUE THREAD

**Issue by liutiemei** [binarywang/weixin-java-pay-demo#35]
### 简要描述
调用WxPayController的原生的统一下单接口输入参数，根据【响应数据】看返回正常，但控制台报了StackOverflowError，debug下来找不到问题所在。

### 版本情况
<weixin-java-pay.version>3.4.0</weixin-java-pay.version>

### 期待结果
返回WxPayUnifiedOrderResult对象

### 重现步骤
1. 接口写死入参：
request.setNonceStr(RandomUtil.getRandomStr());
    request.setBody("商品简单描述");
    request.setOutTradeNo(String.valueOf(System.currentTimeMillis()));//商户订单号
    request.setFeeType("CNY");
    request.setTotalFee(1);
    request.setSpbillCreateIp("183.39.0.159");//终端IP
    request.setTradeType("JSAPI");//交易类型
    request.setOpenid("oYWv41bJPWyjWEQZ5rtGK6XiqJJQ");
    request.setSignType(WxPayConstants.SignType.MD5);
    WxPayUnifiedOrderResult result = wxService.unifiedOrder(request);
2. 手机微信调用unifiedOrder()接口

### 日志
日志放在
https://paste.ubuntu.com/p/b3rRfhGdXM/

**Comment by binarywang** [comment]
日志不全，看不出导致StackOverflowError的源头代码是哪儿

**Comment by 928060115** [comment]
同问，我也遇到这个问题

**Comment by binarywang** [comment]
> 同问，我也遇到这个问题

请提供详细信息
