### ISSUE TITLE
如何正确启用沙箱环境

### ISSUE THREAD

**Issue by DanJesse** [binarywang/weixin-java-pay-demo#36]
如何正确启用沙箱环境
### 简要描述
沙箱环境设置为true
payConfig.setUseSandboxEnv(true);
返回报错，提示签名不对

### 版本情况

* WxJava 版本号:
3.3.0

### 期待结果
正常返回

**Comment by binarywang** [comment]
沙箱环境的文档阅读过没？key是需要使用专门接口获取的

**Comment by DanJesse** [comment]
我知道怎么获取，但是获取到以后怎么操作呢

**Comment by binarywang** [comment]
配置到对应的参数处啊，否则获取有啥意义？

**Comment by DanJesse** [comment]
怎么配置呢
用哪个方法呢

**Comment by binarywang** [comment]
你没读过首页readme吗？

**Comment by binarywang** [comment]
为什么用方法，直接改配置文件对应参数就行

**Comment by DanJesse** [comment]
我一开始配置的，但是还是返回不对，而且请求参数我看的也不是我获取的那个

**Comment by DanJesse** [comment]
这个key获取后怎么配置呢，在哪里配置，

**Comment by DanJesse** [comment]
我是直接set到WxPayUnifiedOrderRequest这个里面了

**Comment by DanJesse** [comment]
我获取的key是db47db57022aef645946c438b144581d
但是到请求数据看不到这个
【请求地址】：https://api.mch.weixin.qq.com/sandboxnew/pay/unifiedorder
【请求数据】：<xml>
  <appid>wxb87d2570e5e5bbc1</appid>
  <mch_id>1515842121</mch_id>
  <nonce_str>1566355935344</nonce_str>
  <sign>2D190A0116A28C42755BE064CC069597</sign>
  <sign_type>MD5</sign_type>
  <body>珊瑚币充值</body>
  <out_trade_no>156612800186351</out_trade_no>
  <total_fee>1000</total_fee>
  <spbill_create_ip>string</spbill_create_ip>
  <notify_url>123</notify_url>
  <trade_type>string</trade_type>
</xml>
【响应数据】：<xml>
  <return_code><![CDATA[FAIL]]></return_code>
  <return_msg><![CDATA[沙箱验证签名失败，请确认沙箱签名key是否正确（通过getsignkey调用生成）]]></return_msg>
</xml>

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/668 你看过这个没有？

**Comment by DanJesse** [comment]
解决了
