### ISSUE TITLE
统一下单，本地环境没有错误，但是部署到测试环境，一直返回返回结果mch_id参数格式错误

### ISSUE THREAD

**Issue by zhx91** [binarywang/weixin-java-pay-demo#38]
<dependency>
        <groupId>com.github.binarywang</groupId>
        <artifactId>weixin-java-pay</artifactId>
        <version>3.3.0</version>
</dependency>

### 简要描述
如题所述，微信支付统一下单时，本地环境测试没有问题，但是在测试环境，一直返回mch_id参数格式错误

本地数据：返回成功
【请求地址】：https://api.mch.weixin.qq.com/pay/unifiedorder
【请求数据】：<xml>
  <appid>*****</appid>
  <mch_id>******</mch_id>
  <nonce_str>1573463359943</nonce_str>
  <sign>F33015C88D0D1C90D8C79C7E4D43DB0F</sign>
  <body>统一下单</body>
  <attach>1191653232132558850</attach>
  <out_trade_no>1572947244649905171</out_trade_no>
  <total_fee>1</total_fee>
  <spbill_create_ip>0:0:0:0:0:0:0:1</spbill_create_ip>
  <time_start>20191111170919</time_start>
  <time_expire>20191112170919</time_expire>
  <notify_url>****/notify</notify_url>
  <trade_type>JSAPI</trade_type>
  <openid>*****</openid>
</xml>

测试数据：
【请求地址】：https://api.mch.weixin.qq.com/pay/unifiedorder
【请求数据】：<xml>
  <nonce_str>1573462191204</nonce_str>
  <sign>183AF85FA774557F2E4C3C837C656C41</sign>
  <body>下单</body>
  <attach>1193806035228254209</attach>
  <out_trade_no>1573460513299111341</out_trade_no>
  <total_fee>1</total_fee>
  <spbill_create_ip>61.148.244.144</spbill_create_ip>
  <time_start>20191111164951</time_start>
  <time_expire>20191112164951</time_expire>
  <notify_url>****/notify</notify_url>
  <trade_type>JSAPI</trade_type>
  <openid>****</openid>
</xml>
【响应数据】：<xml><return_code><![CDATA[FAIL]]></return_code><return_msg><![CDATA[mch_id参数格式错误]]></return_msg></xml>
2019-11-11 16:49:51.373 ERROR 16460 --- [nio-9090-exec-3] c.g.b.w.b.r.WxPayUnifiedOrderResult      : 
结果业务代码异常，返回结果：{return_msg=mch_id参数格式错误, return_code=FAIL},
返回代码：FAIL，返回信息：mch_id参数格式错误

没有提交mch_id

### 版本情况

* WxJava 版本号:
3.5.0   3.3.0 都试过了

**Comment by a2420221622** [comment]
我今天试了一下也遇到这个问题，后来发现是没有把配置文件里的值赋值上去，但是手动set是可以不会报错，但是配置文件按照Demo 就一直null，请问你是怎么解决的
