### ISSUE TITLE
有没有微信卡券核销回到相关的内容呢？

### ISSUE THREAD

**Issue by Xubo12345** [binarywang/weixin-java-pay-demo#39]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
这个跟微信支付一毛钱关系都没有啊，没啥在这里问？
你要去公众号模块去看。
