### ISSUE TITLE
EntPayResult和BaseWxPayResult都定义了mchId字段

### ISSUE THREAD

**Issue by hzh2005525** [binarywang/weixin-java-pay-demo#42]
简要描述
_EntPayResult和BaseWxPayResult都定义了mchId字段

版本情况
<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>weixin-java-pay</artifactId>
    <version>3.6.0</version>
</dependency>

期待结果
gson.toJson(entPayResult)正常打印日志

实际情况
gson.toJson(entPayResult)报异常

重现步骤
gson.toJson(entPayResult)

 日志
https://paste.ubuntu.com/p/QqdRRR8wYk/

**Comment by binarywang** [comment]
你这个issue提的位置不对呢，应该在WxJava项目里吧

**Comment by hzh2005525** [comment]
提错位置了

**Comment by binarywang** [comment]
gson的问题，建议不要使用gson转换这个bean。
