### ISSUE TITLE
分账结果查询结果提示“验证签名失败”，后来我咨询过微信技术助手，这个接口不能加多余的参数，然后我自己写了个简单的原生请求，只保留开发文档的参数提交就正常了（你们的请求多加了appid参数，手动设置为null一样会验证失败）

### ISSUE THREAD

**Issue by SimonLong** [binarywang/weixin-java-pay-demo#43]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
为啥不把内容放正文呢

**Comment by SimonLong** [comment]
不好意思，第一次提交issue




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binary Wang"<notifications@github.com&gt;; 
发送时间: 2020年3月9日(星期一) 下午4:28
收件人: "binarywang/weixin-java-pay-demo"<weixin-java-pay-demo@noreply.github.com&gt;; 
抄送: "繁星"<1369131941@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [binarywang/weixin-java-pay-demo] 分账结果查询结果提示“验证签名失败”，后来我咨询过微信技术助手，这个接口不能加多余的参数，然后我自己写了个简单的原生请求，只保留开发文档的参数提交就正常了（你们的请求多加了appid参数，手动设置为null一样会验证失败） (#43)




为啥不把内容放正文呢

**Comment by binarywang** [comment]
不知道你是否使用最新版本，这个问题在WxJava的#1378 已经修复

**Comment by SimonLong** [comment]
我之前有更新3.7.0测试，还有你们的分账对应doc没有对应更新，所以一直以为没有解决，又用回3.6.0了，咨询腾讯助手后忘记再用3.7.0版本手动设置appid为null测试。其实我觉得应该内部封装就设置为null，从而避免调用的人不清楚此规则。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 下午4:29
收件人:&nbsp;"binarywang/weixin-java-pay-demo"<weixin-java-pay-demo@noreply.github.com&gt;;
抄送:&nbsp;"繁星"<1369131941@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [binarywang/weixin-java-pay-demo] 分账结果查询结果提示“验证签名失败”，后来我咨询过微信技术助手，这个接口不能加多余的参数，然后我自己写了个简单的原生请求，只保留开发文档的参数提交就正常了（你们的请求多加了appid参数，手动设置为null一样会验证失败） (#43)




不知道你是否使用最新版本，这个问题在WxJava的#1378 已经修复
