### ISSUE TITLE
WxPaySendRedpackResult 中是不是少个package字段

### ISSUE THREAD

**Issue by lovesea6688** [binarywang/weixin-java-pay-demo#44]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
SDK相关问题，请把问题统一提到wxjava项目里，谢谢合作

**Comment by binarywang** [comment]
另外新提交issue时请给出官方文档地址，如果文档里未提及，请给出你的测试用例
