### ISSUE TITLE
com.thoughtworks.xstream jar包冲突

### ISSUE THREAD

**Issue by patern** [binarywang/weixin-java-pay-demo#45]
### 简要描述
com.thoughtworks.xstream 一个引用1.411.1 一个是1.4.9 

### 3.7.0

* WxJava 版本号:
3.6.0, 3.7.0

### 实际情况
__尽量详细描述__

### 重现步骤

![image](https://user-images.githubusercontent.com/3724797/76484614-399fe780-6455-11ea-8231-e4e3ea30bbb6.png)
而weixin-java-common-3.6.0.jar 中XStreamInitializer
 XStream xstream = new XStream(new PureJavaReflectionProvider(), XPP_DRIVER);
    xstream.ignoreUnknownElements();
    xstream.setMode(XStream.NO_REFERENCES);
    XStream.setupDefaultSecurity(xstream);
    xstream.allowTypesByWildcard(new String[]{
      "me.chanjar.weixin.**", "cn.binarywang.wx.**", "com.github.binarywang.**"
    });
在1.4.9中XStream.setupDefaultSecurity()方法已经没有了

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
请保证同一版本，是你自己的使用问题，纠正过来即可
