### ISSUE TITLE
引完jar 启动项目 报错

### ISSUE THREAD

**Issue by songmingfeng** [binarywang/weixin-java-pay-demo#53]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
Parameter 0 of constructor in *.WxPayController required a bean of type 'com.github.binarywang.wxpay.service.WxPayService' that could not be found.

### 版本情况

* WxJava 版本号:
3.0.7

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__日志内容如果过多，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
你没参考本demo吗？
