### ISSUE TITLE
获取微信请求数据，方便接口调用方获取处理

### ISSUE THREAD

**Issue by songmingfeng** [binarywang/weixin-java-pay-demo#56]
WxPayApiData getWxApiData
这个方法怎么用

**Comment by binarywang** [comment]
直接调用呗

**Comment by songmingfeng** [comment]
直接调用报null指针

**Comment by songmingfeng** [comment]
> 直接调用呗
报null指针

**Comment by songmingfeng** [comment]
报null指针怎么解决





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Binary Wang <notifications@github.com&gt;
发送时间: 2020年6月16日 13:56
收件人: binarywang/weixin-java-pay-demo <weixin-java-pay-demo@noreply.github.com&gt;
抄送: songmingfeng <527243523@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[binarywang/weixin-java-pay-demo] 获取微信请求数据，方便接口调用方获取处理 (#56)

**Comment by binarywang** [comment]
com.github.binarywang.wxpay.config.WxPayConfig#ifSaveApiData

看下这个属性，设置为true，就可以使用了

**Comment by songmingfeng** [comment]
谢谢



一起快乐


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 下午2:17
收件人:&nbsp;"binarywang/weixin-java-pay-demo"<weixin-java-pay-demo@noreply.github.com&gt;;
抄送:&nbsp;"听雨轩っ、"<527243523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [binarywang/weixin-java-pay-demo] 获取微信请求数据，方便接口调用方获取处理 (#56)





 
com.github.binarywang.wxpay.config.WxPayConfig#ifSaveApiData
 
看下这个属性，设置为true，就可以使用了
