### ISSUE TITLE
直接调用呗

### ISSUE THREAD

**Issue by songmingfeng** [binarywang/weixin-java-pay-demo#57]
直接调用呗

_Originally posted by @binarywang in https://github.com/binarywang/weixin-java-pay-demo/issues/56#issuecomment-644547686_

**Comment by songmingfeng** [comment]
直接调用报null指针

**Comment by binarywang** [comment]
啥玩意？

**Comment by songmingfeng** [comment]
WxPayApiData wxApiData = this.payService.getWxApiData();
获取的是null


我这个测试类BaseWxPayServiceImplTest

调的

一起快乐


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 下午2:07
收件人:&nbsp;"binarywang/weixin-java-pay-demo"<weixin-java-pay-demo@noreply.github.com&gt;;
抄送:&nbsp;"听雨轩っ、"<527243523@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [binarywang/weixin-java-pay-demo] 直接调用呗 (#57)





 
啥玩意？
