### ISSUE TITLE
weixin-java-pay 支付成功回调接口，解析xml时，出错

### ISSUE THREAD

**Issue by zhizunyoulan** [binarywang/weixin-java-pay-demo#58]
#weixin-java-pay 支付成功回调接口，解析xml时，出错

### 简要描述
通过反射获取WxPayOrderNotifyResult和其父类中的字段时，获取了两个serialVersionUID字段，导致后面的解析出错，3.8.0版本中没有这个错误，因为这个版本中父类BaseWxPayResult没有serialVersionUID字段。

### 版本情况
*   3.8.2.B

### 期待结果
去掉父类BaseWxPayResult中的serialVersionUID字段，或者修改通过反射获取字段的代码，从获取的Map中去掉一个serialVersionUID。

**Comment by binarywang** [comment]
此问题新版本会修复
