### ISSUE TITLE
调用unifiedOrder 接口的时候发现报这个错误

### ISSUE THREAD

**Issue by IdoFree** [binarywang/weixin-java-pay-demo#6]
com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderResult cannot be cast to com.github.binarywang.wxpay.bean.result.WxPayBaseResult

调用过程如下：
WxPayController.unifiedOrder ->wxService.unifiedOrder(request)->WxPayBaseResult.fromXML(responseContent, WxPayUnifiedOrderResult.class) 

具体报错的地方就是fromXML转换类型的时候出问题

public static T fromXML(String xmlString, Class clz) {
XStream xstream = XStreamInitializer.getInstance();
xstream.processAnnotations(clz);
T result = (T) xstream.fromXML(xmlString);
result.setXmlString(xmlString);
return result;
}

**Comment by binarywang** [comment]
你核对下代码版本吧，用项目最新版本试试看

**Comment by binarywang** [comment]
com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderResult cannot be cast to com.github.binarywang.wxpay.bean.result.WxPayBaseResult
这种错误，按目前的代码不应该出现。

**Comment by IdoFree** [comment]
我也觉得奇怪，版本应该市最新的2.7.0
会不会市jdk 的问题，我用的1.8

**Comment by binarywang** [comment]
一样的，项目默认用的就是1.8的jdk

**Comment by binarywang** [comment]
@IdoFree 
问题还存在吗？

**Comment by binarywang** [comment]
没人理睬，那就先关闭吧

**Comment by fbchen** [comment]
假如需要从 WxPay***Result 继承，创建新的子类，这些子类就会出现 cannot be cast 的异常，如下代码：
```java
public class Test1 {
	
	@XStreamAlias("xml")
	public class ULinePayUnifiedOrderResult extends WxPayUnifiedOrderResult {
		// some fields and getters / setters
	}

	public static void main(String[] args) {
		String xml = "<xml><return_code>SUCCESS</return_code><return_msg>OK</return_msg></xml>";
		
		ULinePayUnifiedOrderResult result = WxPayBaseResult.fromXML(xml, ULinePayUnifiedOrderResult.class);
		System.out.println(result);
	}
}
```

报错信息：
Exception in thread "main" java.lang.ClassCastException: com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderResult cannot be cast to com.letsaycoffee.onlytest.Test1$ULinePayUnifiedOrderResult
	at com.letsaycoffee.onlytest.Test1.main(Test1.java:22)


解决办法是重构 `fromXML` 方法，如下：

```java
	/**
	 * 从xml字符串创建bean对象
	 */
	@SuppressWarnings("unchecked")
	public static <T extends WxPayBaseResult> T fromXML(String xmlString, Class<T> clz) {
		XStream xstream = XStreamInitializer.getInstance();
		xstream.processAnnotations(clz);
		xstream.alias("xml", clz); // <---- 增加此行代码
		T result = (T) xstream.fromXML(xmlString);
		result.setXmlString(xmlString);
		return result;
	}
```
