### ISSUE TITLE
调用unifiedOrder这个接口的时候,提示签名错误,我在报错信息里面看了下请求参数,<xml>的顺序好像不对,但是又不知道怎么改,请问一下,这个接口的参数应该怎么set,我这边暂时还没有前端参与,就直接把写死的参数set进去的

### ISSUE THREAD

**Issue by 1622201743** [binarywang/weixin-java-pay-demo#61]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__日志内容如果过多，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by 1622201743** [comment]
![1594610516](https://user-images.githubusercontent.com/68050425/87267776-2b450380-c4fb-11ea-8252-d4cdc4767da7.jpg)

**Comment by binarywang** [comment]
签名错误一般是你配置的问题，appid或者密钥搞错了，请仔细核查下

**Comment by binarywang** [comment]
跟顺序没 关系，签名的问题

**Comment by 1622201743** [comment]
> 跟顺序没 关系，签名的问题

已经解决了,误打误撞,应该是我的秘钥没有写在配置文件中,谢谢哈
