### ISSUE TITLE
支付问题

### ISSUE THREAD

**Issue by BigRabbit2** [binarywang/weixin-java-pay-demo#62]
入参前端传入金额单位不是元嘛，要转为分，那么WxPayUnifiedOrderRequest的totalFee字段类型为Integer是不是有问题呢？元的话可能存在小数啥的

**Comment by binarywang** [comment]
大哥，看下官方文档不可以吗？

**Comment by binarywang** [comment]
前端传的元，你把它转换成分不就行了嘛

**Comment by BigRabbit2** [comment]
前端传元可能会有0.5元这种情况 WxPayUnifiedOrderRequest请求参数为Integer不是会把小数部分省略了？

**Comment by BigRabbit2** [comment]
> 前端传的元，你把它转换成分不就行了嘛

前端传元可能会有0.5元这种情况 WxPayUnifiedOrderRequest请求参数为Integer不是会把小数部分省略了？

**Comment by binarywang** [comment]
那是你自己的问题，要么改前端，要么改后端，这个Demo只是给你演示接口怎么调用，不要太死脑筋了
