### ISSUE TITLE
 weixin-java-pay-demo项目的pom文件可去掉jodd-http的依赖

### ISSUE THREAD

**Issue by belizer** [binarywang/weixin-java-pay-demo#64]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）
 weixin-java-pay-demo项目的pom文件可去掉jodd-http的依赖
### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__
因为weixin-pay项目已经提供jodd-http的依赖，且作用域范围为provided。而现在weixin-java-pay-demo最新版本中的jodd-http还为3.9.1，没有weixin-pay项目需要的resourceUtil类，所以weixin-java-pay-demo运行会报noClassDefError.

### 版本情况
weixin-java-pay-demo 1.0.0-SNAPSHOT
* WxJava 版本号:
3.8.0

**Comment by binarywang** [comment]
感谢指出，不过描述错了吧，默认依赖scope是compile的，把本demo里的去掉就可以了
