### ISSUE TITLE
希望WxPayOrderQueryResult 的属性和方法可以添加一些注释

### ISSUE THREAD

**Issue by mirror6Y** [binarywang/weixin-java-pay-demo#65]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
友好的建议，本人英文水平较差，查看WxPayOrderQueryResult 的属性有些吃力

### 版本情况

* WxJava 版本号:3.8.0

### 期待结果
希望添加适量注释

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__日志内容如果过多，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by mirror6Y** [comment]
希望采纳

**Comment by binarywang** [comment]
你确定看源码了吗？源码里注释很明确

https://github.com/Wechat-Group/WxJava/blob/master/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/result/WxPayOrderQueryResult.java

**Comment by binarywang** [comment]
另外也不需要下载源码，看javadoc其实就足够了

**Comment by mirror6Y** [comment]
不好意思，我再研究一下。给你添麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binary Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 下午3:15
收件人: "binarywang/weixin-java-pay-demo"<weixin-java-pay-demo@noreply.github.com&gt;; 
抄送: "mirror6"<1766650501@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [binarywang/weixin-java-pay-demo] 希望WxPayOrderQueryResult 的属性和方法可以添加一些注释 (#65)





 
另外也不需要下载源码，看javadoc其实就足够了

**Comment by mirror6Y** [comment]
之前没有下载源码，谢谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binary Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 下午3:15
收件人: "binarywang/weixin-java-pay-demo"<weixin-java-pay-demo@noreply.github.com&gt;; 
抄送: "mirror6"<1766650501@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [binarywang/weixin-java-pay-demo] 希望WxPayOrderQueryResult 的属性和方法可以添加一些注释 (#65)





 
另外也不需要下载源码，看javadoc其实就足够了
