### ISSUE TITLE
关于同时使用app和小程序支付

### ISSUE THREAD

**Issue by JerryWzq** [binarywang/weixin-java-pay-demo#68]
# 一个springboot项目同时使用微信app支付和小程序支付

### 简要描述
项目需要微信app支付和小程序支付，使用的wx-java-pay-spring-boot-starter，是否支持同时配置小程序和app的appId,
还是需要重新新建一个项目做小程序支付

### 版本情况

* wx-java-pay-spring-boot-starter 版本号: 3.7.8.B

**Comment by binarywang** [comment]
你的问题跟这个demo也没关系啊。
首先starter是方便快速接入单一功能的，而你的情况比较复杂，建议参考本demo，配置多个config和service即可实现功能

**Comment by JerryWzq** [comment]
好的，谢谢
