### ISSUE TITLE
版本 3.9.0 统一下单接口 没有返回加密的参数时timeStamp参数，前端拿不到后端加密时timeStamp，前端调微信支付接口提示签名失败

### ISSUE THREAD

**Issue by zhougz9527** [binarywang/weixin-java-pay-demo#69]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__日志内容如果过多，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
请使用createOrder方法
