### ISSUE TITLE
请求合单关闭订单API，子单信息缺少参数sub_mchid

### ISSUE THREAD

**Issue by Bigbear-Smallbear** [binarywang/weixin-java-pay-demo#90]
### 简要描述
1.使用WxPayService中的closeCombine方法，请求合单关闭订单API，子单信息缺少参数sub_mchid;
2. EcommerceService中只有关闭单笔交易订单的方法，没有关闭合单的方法，建议补上；

### 版本情况

* WxJava 版本号:4.2.0

**Comment by binarywang** [comment]
请到WxJava项目提问题，如果你有现成代码修复，建议直接提交PR代码
