### ISSUE TITLE
V3下单 提示((WxPayConfig)this).privateCertPath 不可逆 无法自动更新证书

### ISSUE THREAD

**Issue by DearestLove** [binarywang/weixin-java-pay-demo#92]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）
V3下单 提示((WxPayConfig)this).privateCertPath 不可逆 无法自动更新证书
### 简要描述
__明确描述下你所遇到的问题，（友情提示，如果确认属于bug，请参考贡献指南直接提交PR，省的花费时间在这里描述问题，非常感谢配合）__

### 版本情况

* WxJava 版本号:
4.2.0

### 期待结果
__尽量详细描述__

### 实际情况
__尽量详细描述__

### 重现步骤
正常 v3crateOrder

### 日志
__日志内容如果过多，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__
((WxPayConfig)this).privateCertPath Inconvertible types; cannot cast 'com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl' to 'com.github.binarywang.wxpay.config.WxPayConfig'

**Comment by binarywang** [comment]
你这错误跟你代码有关系吧？

**Comment by DearestLove** [comment]
> 你这错误跟你代码有关系吧？

按照demo来配置的 其他的都没有改过 

这是v3的配置 
```
        payConfig.setApiV3Key(StringUtils.trimToNull(this.properties.getMchV3Key()));
        payConfig.setCertSerialNo(StringUtils.trimToNull(this.properties.getCertSerialNo()));
        payConfig.setPrivateKeyPath(StringUtils.trimToNull(this.properties.getPrivateKeyPath()));
        payConfig.setPrivateCertPath(StringUtils.trimToNull(this.properties.getPrivateCertPath()));
```

这是下单
```
       WxPayUnifiedOrderV3Request request = new WxPayUnifiedOrderV3Request();
        request.setAppid(payProperties.getAppId());
        request.setMchid(payProperties.getMchId());
        request.setDescription("补款");
        String s = RandomUtil.randomString(32);
        request.setOutTradeNo(s);
        request.setAmount(new WxPayUnifiedOrderV3Request.Amount().setTotal(100));
        request.setNotifyUrl(payProperties.getNotifyUrl());

        this.wxService.createOrderV3(TradeTypeEnum.NATIVE, request);

```

**Comment by DearestLove** [comment]
> 你这错误跟你代码有关系吧？

主要这个自动更新 cert 失败 ，payConfig.setPrivateCertPath 里面存放的是 classpath：apiclient_cert.pem 是因为这个原因嘛


Auto update cert failed, statusCode = 401,body = {"code":"SIGN_ERROR",

**Comment by DearestLove** [comment]
> 你这错误跟你代码有关系吧？

解决了，真的离谱换个证书就行了 前两天申请的 一样的 不知道为啥不能用

**Comment by DearestLove** [comment]
> 你这错误跟你代码有关系吧？

解决了，真的离谱换个证书就行了 前两天申请的 一样的 不知道为啥不能用
