### ISSUE TITLE
v3 jsapi下单出现错误

### ISSUE THREAD

**Issue by chaobear** [binarywang/weixin-java-pay-demo#97]
Caused by: java.lang.ClassNotFoundException: me.chanjar.weixin.common.util.json.GsonParser

调用的方法：wxService.createOrderV3

**Comment by binarywang** [comment]
很有可能是你common包冲突导致，看看是不是引用了多个版本

**Comment by chaobear** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/51193643/164194473-31f90a7b-9a38-43e7-843c-28c9055a4280.png">

**Comment by binarywang** [comment]
miniapp和pay的版本不一致，导致对应的common包不一致

**Comment by chaobear** [comment]
谢谢
