### ISSUE TITLE
签名错误，请检查后再试

### ISSUE THREAD

**Issue by zhaokejin** [binarywang/weixin-java-pay-demo#99]
![image](https://user-images.githubusercontent.com/13448504/168228120-13d60f51-30c9-40a0-b2c5-7dbd2e5354fd.png)

我从官网校验是校验通过的
![image](https://user-images.githubusercontent.com/13448504/168228463-43ff707c-f5fd-491a-9791-6471c04d197d.png)

这是什么原因呢

**Comment by LMEToken** [comment]
解决了么

**Comment by zhaokejin** [comment]
> 解决了么
没有，不知道哪里的问题，就是校验不过去

**Comment by 1160817999** [comment]
解决了吗？

**Comment by sdrenhao** [comment]
body里的汉字换成英文试试
本地签名是正确的，服务器上如果是汉字可能签名会不一样

**Comment by renanmin** [comment]
这是来自QQ邮箱的疫情自动回复邮件。
 
您好，我最近正在疫情中，无法亲自回复您的邮件。我将在疫情结束后，尽快给您回复。

**Comment by letterZhao** [comment]
我的问题，mchKey填api密钥我填错地方了
